config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :sources
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
require 'securerandom'

class Entry < ApplicationRecord
  belongs_to :source
  delegate :user, to: :source, allow_nil: true

  attr_accessor :attachment

  before_create :ocr

  private

  def ocr
    return unless attachment
    key = "waste_paper.#{SecureRandom.uuid}" 
    File.open(key, 'w+b') do |f|
      f.write attachment.body.decoded 
    end
    self.content = `tesseract #{key} -`.split("\n").map(&:strip).join("\n")
  ensure
    (File.delete(key) rescue nil) if defined?(key)
  end
end

app/models/source.rb
require 'net/imap'

class Source < ApplicationRecord
  belongs_to :user
  has_many :entries

  validates :username, uniqueness: { case_sensitive: false }
  validates :username, :password, :port, :address, :ssl, presence: true
  validates :port, numericality: { only_integer: true }

  def works?
    !mail.disconnected?
  rescue Net::IMAP::NoResponseError => e
    raise e unless e =~ /Authentication failed./
    false
  end

  def mails flags: %w(UNSEEN)
    mail.search(flags).map do |message_id|
      m = Mail.new(mail.fetch(message_id, "RFC822")[0].attr['RFC822'])
      block_given? ? yield(m, message_id) : m
    end
  end

  def entries!
    processing_dir!
    mails do |m, message_id|
      m.attachments.each do |attachment|
        self.entries << Entry.new(attachment: attachment)
      end
      mail.copy(message_id, 'INBOX.Archive')
      mail.store(message_id, '+FLAGS', [:Deleted])
    end
    mail.expunge
  end

  def processing_dir!
    return if mail.list('INBOX.', 'Archive')
    mail.create('INBOX.Archive')
  end

  def mail
    @mail ||= 
      begin
        i = Net::IMAP.new(self.address, self.port, false)
        i.starttls if self.ssl and self.port == 143
        i.authenticate(self.authentication, self.username, self.password) 
        i.select('INBOX')
        i
      end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sources
  has_many :entries, through: :sources
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:source_id, :content)
    end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'Source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:address, :user, :password, :port, :authentication, :ssl, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/entries/_form.html.erb
<%= form_for(entry) do |f| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source_id %>
    <%= f.text_field :source_id %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.source %></td>
        <td><%= entry.content %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @entry.source %>
</p>

<p>
  <strong>Content:</strong>
  <%= @entry.content %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WastePaper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sources/_form.html.erb
<%= form_for(source) do |f| %>
  <% if source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :port %>
    <%= f.number_field :port %>
  </div>

  <div class="field">
    <%= f.label :authentication %>
    <%= f.text_field :authentication %>
  </div>

  <div class="field">
    <%= f.label :ssl %>
    <%= f.check_box :ssl %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Editing Source</h1>

<%= render 'form', source: @source %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sources</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>User</th>
      <th>Password</th>
      <th>Port</th>
      <th>Authentication</th>
      <th>Ssl</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sources.each do |source| %>
      <tr>
        <td><%= source.address %></td>
        <td><%= source.user %></td>
        <td><%= source.password %></td>
        <td><%= source.port %></td>
        <td><%= source.authentication %></td>
        <td><%= source.ssl %></td>
        <td><%= source.user %></td>
        <td><%= link_to 'Show', source %></td>
        <td><%= link_to 'Edit', edit_source_path(source) %></td>
        <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source', new_source_path %>

app/views/sources/new.html.erb
<h1>New Source</h1>

<%= render 'form', source: @source %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @source.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @source.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @source.password %>
</p>

<p>
  <strong>Port:</strong>
  <%= @source.port %>
</p>

<p>
  <strong>Authentication:</strong>
  <%= @source.authentication %>
</p>

<p>
  <strong>Ssl:</strong>
  <%= @source.ssl %>
</p>

<p>
  <strong>User:</strong>
  <%= @source.user %>
</p>

<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>